"""add_statement_status_and_logs

Revision ID: f0a3d20cfce5
Revises: 2e773595c90a
Create Date: 2026-04-12 14:28:20.256799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0a3d20cfce5'
down_revision: Union[str, None] = '2e773595c90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('statements', sa.Column('error_log', sa.String(length=1024), nullable=True))
    op.alter_column('statements', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('statements', 'error_log')
    op.drop_column('statements', 'status')
    # ### end Alembic commands ###
